alias finder='open -a finder'
alias ll='ls -alh'
alias lll='ls -lasht'
alias c='clear'
alias g='git'
alias gs='c; git status'
alias gss='c; git status -s'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdt='git difftool'
alias ga='git add'
alias gr='git checkout --'
alias gpr='git pr'
alias gpom='git pull origin master'
alias gprom='git pull --rebase origin master'
alias ..='cd ..'
alias src='cd ~/src'
alias relev='cd ~/src/relevancy'
alias hist='history'
alias untar='tar xvfz'
alias fs="stat -f \"%z bytes\"" # File size
alias please='sudo'

# prevent zsh autocorrection on the following:
alias ssh='nocorrect ssh'
